package dbutils

const SELECT_TRAIN_BY_ID = "SELECT ID, DRIVER_NAME, OPERATING_STATUS FROM train WHERE id=?"
const INSERT_TRAIN = "INSERT INTO train (DRIVER_NAME, OPERATING_STATUS) VALUES (?, ?)"
const DELETE_TRAIN_BY_ID = "DELETE FROM train WHERE id=?"