package dbutils

/* Train statements */
const SELECT_TRAIN_BY_ID = "SELECT ID, DRIVER_NAME, OPERATING_STATUS FROM train WHERE id=?"
const INSERT_TRAIN = "INSERT INTO train (DRIVER_NAME, OPERATING_STATUS) VALUES (?, ?)"
const DELETE_TRAIN_BY_ID = "DELETE FROM train WHERE id=?"

/* Station statements */
const SELECT_STATION_BY_ID = "SELECT ID, NAME, CAST(OPENING_TIME AS CHAR), CAST(CLOSING_TIME AS CHAR) FROM station WHERE ID=?"
const INSERT_STATION = "INSERT INTO station (NAME, OPENING_TIME, CLOSING_TIME) VALUES (?, ?, ?)"
const DELETE_STATION_BY_ID = "DELETE FROM station WHERE id=?"