version: '3'

services:
  app:
    build:
      context: ./bookServer
      dockerfile: Dockerfile
    expose:
      - 8000
    restart: unless-stopped
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge